### ISSUE TITLE
Issues with package in Kaggle

### ISSUE THREAD

**Issue by bjoernholzhauer** [EagerAI/fastai#139] opened 2021-07-24 13:19 UTC
Thanks again for doing this package. Since you seem to use Kaggle notebooks yourself, do you know what's up with the installed R package that is now part of the standard R Kaggle set-up? I tried a few things and just could not get it to work. It looks to me like the python `fastai` package is missing in the background (I also [posted this on Kaggle](https://www.kaggle.com/product-feedback/254217)), but my attempt to simply use `fastai::install_fastai(gpu = FALSE, cuda_version = '10.1', overwrite = FALSE)` failed. Do you know how to get this to work (great if you could share that)? I would of course also understand if you feel that fixing Kaggle's setup is not your problem.

**Comment by turgut090** [comment] 2021-07-24 17:32
Hi. Thanks.
I just fixed some bugs and created notebooks. Please see:
Colab - https://colab.research.google.com/drive/1JDpKnf8RFyeydsZJWHjtFlKujUG925dI?usp=sharing
Kaggle - https://www.kaggle.com/henry090/test-fast-ai-from-r-2-0-9?scriptVersionId=68929439
@bjoernholzhauer

**Comment by bjoernholzhauer** [comment] 2021-07-28 13:09
That Kaggle notebook works just fine for me, but the moment I change `library(magrittr)` to `library(tidyverse)` (which would more or less be my default when I'll need lots of the tidyverse packages, anyway), I get this:
```
Warning message in base::nchar(wide_chars$test, type = "width"):
“internal error -5 in R_decompress1”
Error: package or namespace load failed for ‘tidyverse’:
 .onAttach failed in attachNamespace() for 'tidyverse', details:
  call: base::nchar(wide_chars$test, type = "width")
  error: lazy-load database '/usr/local/lib/R/site-library/cli/R/sysdata.rdb' is corrupt
Traceback:

1. library(tidyverse)
2. tryCatch({
 .     attr(package, "LibPath") <- which.lib.loc
 .     ns <- loadNamespace(package, lib.loc)
 .     env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)
 . }, error = function(e) {
 .     P <- if (!is.null(cc <- conditionCall(e))) 
 .         paste(" in", deparse(cc)[1L])
 .     else ""
 .     msg <- gettextf("package or namespace load failed for %s%s:\n %s", 
 .         sQuote(package), P, conditionMessage(e))
 .     if (logical.return) 
 .         message(paste("Error:", msg), domain = NA)
 .     else stop(msg, call. = FALSE, domain = NA)
 . })
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. value[[3L]](cond)
6. stop(msg, call. = FALSE, domain = NA)
```
Interestingly, I can load all core tidyverse packages individually without any issue (in case that helps identify what is going on).

**Comment by turgut090** [comment] 2021-07-29 10:25
I reran the session and saw that I cannot reproduce your issue. ```library(tidyverse)``` did not throw any error. fastai from CRAN (not from Github) probably helped.  https://www.kaggle.com/henry090/test-fast-ai-from-r-2-0-9

**Comment by bjoernholzhauer** [comment] 2021-07-29 14:12
I can confirm: with the version installing from CRAN the problem has also gone away for me.

**Comment by turgut090** [comment] 2021-07-30 16:08
That's great! We can close this issue, then. Feel free to reopen.

Best,
Turgut

**Closed by turgut090** 2021-07-30 16:08 UTC
